<?php
require_once __DIR__ . "/fpdf/fpdf.php";

function prTxt($value){
    $value = str_replace(["\r\n", "\r"], "\n", (string)($value ?? ''));
    $converted = @iconv('UTF-8', 'windows-1252//TRANSLIT', $value);
    return $converted !== false ? $converted : preg_replace('/[^\x09\x0A\x0D\x20-\x7E]/', '', $value);
}

function partRequestItems($mysqli, $request){
    $items = [];
    $requestDbId = (int)($request['id'] ?? 0);
    if($mysqli && $requestDbId > 0){
        $stmt = $mysqli->prepare("SELECT item_number,ticket_number,part_number,description FROM part_request_items WHERE part_request_id=? ORDER BY item_number,id");
        if($stmt){
            $stmt->bind_param('i', $requestDbId);
            $stmt->execute();
            $result = $stmt->get_result();
            while($row = $result->fetch_assoc()){ $items[] = $row; }
        }
    }
    if(!$items && trim((string)($request['part_number'] ?? '')) !== ''){
        $items[] = [
            'item_number' => 1,
            'ticket_number' => $request['ticket_number'] ?? '',
            'part_number' => $request['part_number'] ?? '',
            'description' => $request['description'] ?? ''
        ];
    }
    return $items;
}

class PartRequestDocumentPDF extends FPDF {
    function NbLines($width, $text){
        $cw = &$this->CurrentFont['cw'];
        $maxWidth = ($width - 2 * $this->cMargin) * 1000 / $this->FontSize;
        $text = str_replace("\r", '', prTxt($text));
        $length = strlen($text);
        if($length && $text[$length - 1] === "\n"){ $length--; }
        $separator = -1; $i = 0; $lineStart = 0; $lineWidth = 0; $lines = 1;
        while($i < $length){
            $character = $text[$i];
            if($character === "\n"){ $i++; $separator = -1; $lineStart = $i; $lineWidth = 0; $lines++; continue; }
            if($character === ' '){ $separator = $i; }
            $lineWidth += $cw[$character] ?? 0;
            if($lineWidth > $maxWidth){
                if($separator === -1){ if($i === $lineStart){ $i++; } } else { $i = $separator + 1; }
                $separator = -1; $lineStart = $i; $lineWidth = 0; $lines++;
            } else { $i++; }
        }
        return $lines;
    }

    function Row($data, $widths, $lineHeight = 6, $fill = false){
        $lines = 1;
        foreach($data as $index => $value){ $lines = max($lines, $this->NbLines($widths[$index], (string)$value)); }
        $height = max(8, $lineHeight * $lines);
        if($this->GetY() + $height > $this->PageBreakTrigger){ $this->AddPage(); }
        foreach($data as $index => $value){
            $width = $widths[$index]; $x = $this->GetX(); $y = $this->GetY();
            $this->Rect($x, $y, $width, $height, $fill ? 'DF' : 'D');
            $this->MultiCell($width, $lineHeight, prTxt($value), 0, 'L');
            $this->SetXY($x + $width, $y);
        }
        $this->Ln($height);
    }

    function Footer(){
        $this->SetY(-12);
        $this->SetFont('Arial', 'I', 8);
        $this->SetTextColor(90, 90, 90);
        $this->Cell(0, 6, 'This document was automatically generated by Crossroad System.', 0, 0, 'C');
    }
}

function buildPartRequestPdf($request, $items = []){
    if(!$items){
        $items = $request['items'] ?? [];
        if(!$items && trim((string)($request['part_number'] ?? '')) !== ''){
            $items[] = ['item_number'=>1,'ticket_number'=>$request['ticket_number'] ?? '','part_number'=>$request['part_number'] ?? '','description'=>$request['description'] ?? ''];
        }
    }
    $pdf = new PartRequestDocumentPDF('P', 'mm', 'A4');
    $pdf->SetMargins(16, 15, 16);
    $pdf->SetAutoPageBreak(true, 18);
    $pdf->AddPage();
    $pdf->SetFillColor(25, 25, 25);
    $pdf->Rect(16, 15, 178, 22, 'F');
    $pdf->SetTextColor(255, 255, 255);
    $pdf->SetFont('Arial', 'B', 16);
    $pdf->SetXY(20, 20);
    $pdf->Cell(170, 7, 'CSSB - PART REQUEST FORM', 0, 1, 'C');
    $pdf->SetFont('Arial', '', 9);
    $pdf->SetX(20);
    $pdf->Cell(170, 5, 'Part ordering request', 0, 1, 'C');
    $pdf->Ln(10);
    $pdf->SetTextColor(0, 0, 0);
    $pdf->SetFillColor(255, 193, 7);
    $pdf->SetFont('Arial', 'B', 11);
    $pdf->Cell(178, 8, '1. REQUEST DETAILS', 1, 1, 'L', true);
    foreach(['Request ID'=>'request_id','Request Date'=>'request_date','Requested By'=>'requested_by','Purpose'=>'purpose'] as $label=>$key){
        $pdf->SetFont('Arial', 'B', 9);
        $pdf->SetFillColor(245, 246, 248);
        $pdf->Cell(43, 9, prTxt($label), 1, 0, 'L', true);
        $pdf->SetFont('Arial', '', 9);
        $value = prTxt($request[$key] ?? '');
        if($key === 'purpose'){
            $x = $pdf->GetX(); $y = $pdf->GetY();
            $height = max(9, 5.5 * $pdf->NbLines(135, $value));
            $pdf->Rect($x, $y, 135, $height);
            $pdf->MultiCell(135, 5.5, $value, 0, 'L');
        } else { $pdf->Cell(135, 9, $value, 1, 1); }
    }
    $pdf->Ln(7);
    $pdf->SetFillColor(255, 193, 7);
    $pdf->SetFont('Arial', 'B', 11);
    $pdf->Cell(178, 8, '2. ITEMS TO ORDER', 1, 1, 'L', true);
    $widths = [13, 38, 38, 89];
    $pdf->SetFont('Arial', 'B', 8.5);
    $pdf->SetFillColor(245, 246, 248);
    $pdf->Row(['No.', 'Ticket Number', 'Part Number', 'Description'], $widths, 6, true);
    $pdf->SetFont('Arial', '', 8.5);
    foreach($items as $index => $item){
        $pdf->Row([
            (string)($item['item_number'] ?? ($index + 1)),
            $item['ticket_number'] ?? '',
            $item['part_number'] ?? '',
            $item['description'] ?? ''
        ], $widths, 5.5);
    }
    return $pdf->Output('S');
}
?>
